import type { DownloadItem, SidebarSection } from "../types";

export const mockDownloads: DownloadItem[] = [
  {
    id: "1",
    name: "blender-4.3.0-linux-x64",
    extension: "tar.xz",
    sizeBytes: 412 * 1024 * 1024,
    downloadedBytes: 268 * 1024 * 1024,
    speedBytesPerSec: 9.4 * 1024 * 1024,
    etaSeconds: 16,
    status: "downloading",
    segments: 16,
    activeSegments: 6,
    source: "download.blender.org",
  },
  {
    id: "2",
    name: "gb-survey-footage-drone-4k",
    extension: "mp4",
    sizeBytes: 2.1 * 1024 * 1024 * 1024,
    downloadedBytes: 612 * 1024 * 1024,
    speedBytesPerSec: 4.8 * 1024 * 1024,
    etaSeconds: 318,
    status: "downloading",
    segments: 24,
    activeSegments: 9,
    source: "storage.internal.net",
  },
  {
    id: "3",
    name: "rust-1.82.0-x86_64-pc-windows-msvc",
    extension: "msi",
    sizeBytes: 186 * 1024 * 1024,
    downloadedBytes: 186 * 1024 * 1024,
    speedBytesPerSec: 0,
    etaSeconds: null,
    status: "completed",
    segments: 8,
    activeSegments: 0,
    source: "static.rust-lang.org",
  },
  {
    id: "4",
    name: "postgres-16-backup-2026-07",
    extension: "sql.gz",
    sizeBytes: 3.4 * 1024 * 1024 * 1024,
    downloadedBytes: 1.1 * 1024 * 1024 * 1024,
    speedBytesPerSec: 0,
    etaSeconds: null,
    status: "paused",
    segments: 32,
    activeSegments: 0,
    source: "backups.gb-dev.local",
  },
  {
    id: "5",
    name: "figma-design-tokens-export",
    extension: "zip",
    sizeBytes: 48 * 1024 * 1024,
    downloadedBytes: 0,
    speedBytesPerSec: 0,
    etaSeconds: null,
    status: "queued",
    segments: 4,
    activeSegments: 0,
    source: "figma.com",
  },
  {
    id: "6",
    name: "steam-library-update-cache",
    extension: "pkg",
    sizeBytes: 890 * 1024 * 1024,
    downloadedBytes: 140 * 1024 * 1024,
    speedBytesPerSec: 0,
    etaSeconds: null,
    status: "error",
    segments: 12,
    activeSegments: 0,
    source: "cdn.steampowered.com",
  },
  {
    id: "7",
    name: "ielts-prep-audio-lessons-full",
    extension: "rar",
    sizeBytes: 1.2 * 1024 * 1024 * 1024,
    downloadedBytes: 1.2 * 1024 * 1024 * 1024,
    speedBytesPerSec: 0,
    etaSeconds: null,
    status: "completed",
    segments: 16,
    activeSegments: 0,
    source: "mirror.eduresources.io",
  },
];

export const sidebarSections: SidebarSection[] = [
  { id: "all", label: "All downloads", count: mockDownloads.length },
  {
    id: "downloading",
    label: "Downloading",
    count: mockDownloads.filter((d) => d.status === "downloading").length,
  },
  {
    id: "paused",
    label: "Paused",
    count: mockDownloads.filter((d) => d.status === "paused").length,
  },
  {
    id: "completed",
    label: "Completed",
    count: mockDownloads.filter((d) => d.status === "completed").length,
  },
  {
    id: "error",
    label: "Failed",
    count: mockDownloads.filter((d) => d.status === "error").length,
  },
];
